### ISSUE TITLE
BigInt support?

### ISSUE THREAD

**Issue by qntm** [qntm/precise-json#2]
`precise-json` is in a great position to take advantage of [this new `BigInt` jazz](https://developers.google.com/web/updates/2018/05/bigint). Some initial thoughts:

* Testing is kind of hard until `BigInt` support lands in a version of Node.js which we can use...?
* Need a way to detect `BigInt` support at run time
* At stringification time, suppose small integer values such as `0` and `0n` were both stringified as `"0"`. On parsing, we would have no way to work out whether to parse `"0"` as `0` or `0n`. This leads to exactly the kind of ambiguity/information loss which `precise-json` is specifically intended to make impossible: was the original value a number or a `BigInt`? Is there a sensible way to resolve this?

**Comment by bakkot** [comment]
> Testing is kind of hard until BigInt support lands in a version of Node.js which we can use...?

```sh
$ nvm use 10
Now using node v10.13.0 (npm v6.4.1)
$ node -e 'console.log(1n)'
1n
```

> Need a way to detect `BigInt` support at run time

```js
typeof BigInt === 'function' && typeof BigInt(0) === 'bigint'
```

> Is  there a sensible way to resolve this?

In case you haven't seen it, you may be interested in the proposal's [own discussion of this question](https://github.com/tc39/proposal-bigint/issues/24). (Its behavior is to throw.)

**Comment by qntm** [comment]
Funnily enough, `precise-json`'s current behaviour is also to throw in these situations! Seems like a good place to be starting from.

**Comment by qntm** [comment]
My tentative idea at the moment is this:

* Alter `preciseJson.parse`'s behaviour when parsing numeric literals. If the numeric literal is a precise `Number`, return that `Number`. If not, but it is a precise `BigInt`, return that `BigInt` (previous behaviour was to throw). If not, throw.
* Alter `preciseJson.stringify`. `Number`s continue to stringify as before. When stringifying a `BigInt`, if the `BigInt`'s numeric value can be exactly represented as a `Number` (e.g. `BigInt(0)`), **throw**. Otherwise, stringify the `BigInt` in full.

I will be the first to admit that this is a little gross but it is strictly more capable than what `precise-json` currently offers or what `JSON.parse` and `JSON.stringify` currently offer. I think it is about as far as I can go here while respecting the "no ambiguity" goal.

I guess I never properly codified that goal. If you're parsing a string like `'0'` then the ambiguity is in there already - the original value could have been `0`, `-0`, `0n` or *anything* really, depending on the original serialiser, which may not have been `precise-json`. That's not something we can do anything about. However, I think what I would like to aim for is a situation where `x` and `preciseJson.parse(preciseJson.stringify(x))` are programmatically indistinguishable from one another for all `x` where this round trip does not throw an exception, and similarly `y` and `preciseJson.stringify(preciseJson.parse(y))`.

**Comment by qntm** [comment]
Seems as if `eslint`'s lack of support for `BigInt` literals could be a limiting factor here.

**Comment by bakkot** [comment]
> Seems as if eslint's lack of support for BigInt literals could be a limiting factor here.

Looks like you got around this by using the `BigInt` constructor, but for reference, I believe you can work around this by configuring eslint to use [babel-eslint](https://github.com/babel/babel-eslint) as its parser.
